language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - lashifrin@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
  - gem install travis -v 1.8.5 --no-rdoc --no-ri
  - sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - sudo chmod +x /usr/local/bin/ecs-cli
  - export BUILD_NAME=gs-spring-boot-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
  - sh travis_scripts/tag_build.sh
  - sh travis_scripts/build_deploy_to_docker_hub.sh
  - sh travis_scripts/deploy_to_amazon_ecs.sh
env:
  global:
  - secure: hw2igW4A4ShHhcJG0xVqfwsXqjtzqAoTwxPimG2+x3laoHH+WsblWo5oxSPdtsQP7h61qQDP9Vwc1+/PRHlveQ9kqbUpMl0W4qC3dmxU9oNuwisOWAC4UdM0stFYA90p9NhCVRscaWesVWWMcw8nJTzi2iJwVwnSHG0NmaVJMJVG/B53BvJjV+Ig1fGk7Z5KE4fTfkFJbVnVbeTV744O40YaXVQ6qFc5Xk2bD+25f9uYUWL4Se/YoGmYzSiOKA8iuUC7keg7Gbq9gf8rysrd7UbSFkv75GtBRuLOdAuGxSoICUnzy/HDEysz43ONb2iCznNLfaTRCghiveoqphBue9/EI2kJ/McjElIBVH45F78K1lf9k2bvXQ9LzPLivTiYRy0Km+TINtUBPRt+5jbiB1SEZUGmqPM+A37RFOx9FM/pkshMdn4/FVuVVMvH9AvTxlf/7SQSm0H/7rbVzO2XDX/zzFyh8lBBVZ4dZM/uANVrGu01HmmOirWYPT5QMHaQVXCrdVGaUTyjz5h2QRV+5i/BxQ/MJEO4kJrI1NbL4Zplo7TaOgrNhAUOVQmDCBz6ZCKS1Mn19YC6W8FRR3YQcLoHFouwM4TJyeHBEdtW0pgDQBPyqD3uu+Kq2ilorz8Uc8Nsfi7dsPexqIYvVuC7oS3G0G3u1ZmrV9TUm6SBgJc=
  - secure: kheiP6vqvr/PAQ/gct0jWRUdat1SglaezeXGL9RwU1WbHyFnCCLrT6fhfNq81oD17Zks3h7p/arbsOpcNuK1BJH5ou22DOzcR8uy6dLWfo36LnoR60kT1EO7QSXHwPRDH2eD2qdfHbx/5ItM3rwTcPJG9sOjWlQXaMgjBioLfvIq2orpmDR4zyEETm8ZHu1IiFqYwe/1a8F3QVTXZjRpPE9+S2MyZKtLq2P1ea+AuAn5gPnDEIQiYHtSBH168FONnv/HKaWIUhOP0ONAKHxrpllO+RBTx0ioU1cupql+adgxiiWQbUDGmi+/7bJQP4DFHvLLBxmO+aDaO5yIk0WW6J6JBcaMnp7YG65MjhSl0zPNlTwYJ55xV8wk8mJt8az2ERyHoFYg26UbWvA1Rw9VjRSM2eVIlOFkTDVO9qjxmtWKHWgXGve4QCINGSCOvoOG/iAfR5uB3Z1srGmqOF9OCteTZd9pUMnQO2MiEyt2VCuZexIcAgeZqyxsJEAr1kRwMXyg14rEj21UczLoHDD8qPRLEUR5oWdZJWuC37qtO5NnPC+ZncxDJSoyLImp+jQd7ZXSJZx2Py8UEPBIvDTBQ8GVkQS9szuoNnS4ulYcYnO8izf6v0LQ2ToY1C8q0yeFsz/gVz0UfN5MWuAtO5zGfP3fEH5KA+P3dPllyLfLeOs=
  - secure: hT4wzu9aMttd0FuaAOtfaMWEkOW0yotvJytHXfBhwYnVDlJFzbVQtjrcOLLyzNuRC8N8iSpxkBtdRdpAujU0sO+SGw3z1/oi+pYhJoOdjwIGVvWLQ+WmMeKz1dyq4TweBRSkeChkOzY2H85XIUOEl+kBtIkF3WHXuCj+SZaFGFX4mmwPF+J5DHVFntOGr9xurxLc0bpjWRvS4jPaXfTQarhszf8d22SXROnZq3EhIJYGI6Mrpa22EHd4bvNzHnEjugO8enZrfp1dl5ix3x5FFq9Ra7nZe0K+skrPXkGZ/Z1Q9N+D68LMIDbn5C4jKD2TI/lEohFsk4BC59N2xzGWtLuL+Iv0Tg9/Sul2rRv9pyVt2G6Q7Z0kjk7DGbgyEV7ReuJQ4aUxAatofXYxJVQytSur2R0vG0Tgujcjk/cB50Uy5KiHUjrhA15YLNNiteG34r3UJ62izbDujmKiw0r1EwkqDQqIxqPNoVSNNVyYhD99LoqW6ojPc04/ufbNu1QBVm+V2S7tgA3gXTN8ie9d1I2cJHlnEVZzGOJsOT5iGZBddwMecORiY8TyqUYhvsdHxHjMQ4ih62RMzzPMhg+J/N+xBBhM+dCYSc8ommALyynG4tKak/b8ayWeZhXRnG46Cu5wdqYalyvN6Uy8R5YTWD13rDoQvv+pET96nbeZchE=
  - COMMIT=${TRAVIS_COMMIT::8}
dd:
  - secure: Nz2N9dJ6/86/51u59U3CeauOOJz8b9FLblGC1CwBfGKmo7C+CZMg/MS7rQ0E13nHVGjgE/iwvpOnOi1TEg09stdIYoaA/W5Whu6CgTWN7mVHqsvSWRH5XuOb39AAwXZgf5jvt2eJIRPPbR7q1zkmzwqIYXmS1rG/8FSG8dfxsTq077+ffJQyYO3CIaEcuozm4ZihBw8hXYTAktjwESr8JFJzVe6XV7HldLRM1HEEkVuA723ePuG9FJGD/nwIa8vrWRRgC+ckECadFpyvGw9kOIpsL27SdQtqoaXFFv1uLk7HrJl+9hc6CNL3g3aGyZqjGeCz9jgVzI6QbOALVlUNUAOxjoYrUg3b9LBGMYIdy0O98DvDylrYWv6zs4yxiUXDbLBUzinC6B3V4MRvhtUxFbwQwKdfY1YqfIyK6pDGeegXElvx1ZKoG1Q+MomvfKhOANoiPHkmzSEBoniGV5WoEEs6tpdroXslPbHAK9h1f/MRB1FY8lljPni8SFSPPjnMtwJx66qvvvVgFdT1g/zhZjWZGv4V4FwZ1q1qH/MY/QXYyAGHdEEpiJrfmptNMCfTbY3rtRO8l0YGhpOQoKJzEhL9o6/9RyDP6FLtPQVsXtLE3zR/xUzDU/CdaVvM4KwViN9BAp/9AM+6mN7oEXefWHBrjd5kHdQa3LcMg9QxgTk=
